version: "3.1"

services:
  wordpress_container:
    image: wordpress:latest
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_HOST=mysql_container
      - WORDPRESS_DB_NAME=wordpressdb
    depends_on:
      - mysql_container

  mysql_container:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpressdb
